# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeuraSDKSampleApp' do
   use_frameworks!
pod 'NeuraSDKFramework', '~> 4.10.0'

end

target 'Notifications' do
   use_frameworks!


end
